user.properties=User Profile Dev UPDATE!

spring.application.name=user-microservices

spring.datasource.url=jdbc:postgresql://35.227.164.209:5432/gestion_tareas_gml5
spring.datasource.username=gestion_tareas_gml5_user
spring.datasource.password=jixealbfrLP3qWYerOKjY4EXOrL0112j
spring.datasource.driver-class-name=org.postgresql.Driver

## Puerto del microservicio usuarios
server.port=0

eureka.instance.instance-id=${spring.application.name}:${random.uuid}